USE master
IF EXISTS  (SELECT * FROM SYS.databases WHERE NAME = 'QLBH')
BEGIN
	ALTER DATABASE QLBH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE QLBH;
END
GO

CREATE DATABASE QLBH
GO

USE QLBH
GO
--Câu 1
CREATE TABLE KHACHHANG (
MaKhachHang CHAR(4) PRIMARY KEY,
HoTen VARCHAR(40),
DiaChi VARCHAR(50),
SoDT VARCHAR(20),
NgaySinh SMALLDATETIME,
NgayDangKy SMALLDATETIME,
DoanhSo MONEY
)
GO
CREATE TABLE NHANVIEN (
MaNhanVien CHAR(4) PRIMARY KEY,
HoTen VARCHAR(40),
SoDT VARCHAR(20),
NgayVaoLam SMALLDATETIME
)
GO
CREATE TABLE SANPHAM (
MaSanPham CHAR(4) PRIMARY KEY,
TenSanPham VARCHAR(40),
DonViTinh VARCHAR(20),
NuocSanXuat VARCHAR(40),
GiaBan MONEY
)
GO
CREATE TABLE HOADON (
SoHoaDon INT PRIMARY KEY,
NgayMuaHang SMALLDATETIME,
MaKhachHang CHAR(4),
MaNhanVien CHAR(4),
TriGiaHoaDon MONEY,
FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG (MaKhachHang), 
FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN (MaNhanVien)
)
GO
CREATE TABLE CHITIETHOADON (
SoHoaDon INT,
MaSanPham CHAR(4),
SoLuong INT,
 PRIMARY KEY (SoHoaDon,MaSanPham),
 FOREIGN KEY (SoHoaDon) REFERENCES HOADON(SoHoaDon),
 FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(MaSanPham)
)
GO
--Câu 2
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)
GO
--Câu 3
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT
ALTER TABLE KHACHHANG 
ALTER COLUMN LOAIKH VARCHAR(20)
GO
--Câu 4
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100)
GO
--Câu 5
ALTER TABLE SANPHAM
DROP COLUMN GHICHU
GO
--Câu 6 
ALTER TABLE KHACHHANG 
ALTER COLUMN LOAIKH VARCHAR(20)
GO
--Câu 7
ALTER TABLE SANPHAM 
ADD CONSTRAINT CK_DonViTinh CHECK(DonViTinh in ('cay', 'hop', 'cai', 'quyen', 'chuc'))
GO
--Câu 8
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GiaBan CHECK( GiaBan >=500)
GO
--Câu 9 
ALTER TABLE ChiTietHoaDon ADD CONSTRAINT CK_SoLuong CHECK(SoLuong>=1)
GO

--Câu 10
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_NgayDangKy CHECK(NgayDangKy > NgaySinh)
GO
