USE master
IF EXISTS  (SELECT * FROM SYS.databases WHERE NAME = 'QLGV')
BEGIN
	ALTER DATABASE QLGV SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE QLGV;
END
GO

CREATE DATABASE QLGV
GO

USE QLGV
GO
--Câu 1
CREATE TABLE HOCVIEN (
MaHocVien CHAR(4) PRIMARY KEY,
Ho VARCHAR(40),
Ten VARCHAR(40),
NgaySinh SMALLDATETIME,
GioiTinh VARCHAR(3),
NoiSinh VARCHAR(40),
MaLop CHAR(3),
)
GO
CREATE TABLE LOP (
MaLop CHAR(4) PRIMARY KEY,
TenLop VARCHAR(40),
TruongLop CHAR(5),
SiSo TINYINT,
MaGiaoVienChuNhiem CHAR(4),
)
GO
CREATE TABLE KHOA (
MaKhoa CHAR(4) PRIMARY KEY,
TenKhoa VARCHAR(40),
NgayThanhLap SMALLDATETIME,
TruongKhoa CHAR(5),
)
GO
CREATE TABLE GIAOVIEN
(
	MaGiaoVien CHAR(4) PRIMARY KEY,
	Hoten VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GioiTinh VARCHAR(3),
	NgaySinh SMALLDATETIME,
	NgayVaoLam SMALLDATETIME,
	HeSo NUMERIC(4,2),
	MucLuong MONEY,
	MaKhoa CHAR(4) FOREIGN KEY REFERENCES KHOA(MaKhoa),
)
GO
CREATE TABLE MONHOC
(
	MaMonHoc VARCHAR(10) PRIMARY KEY,
	TenMonHoc VARCHAR(40),
	TinChiLiThuyet TINYINT,
	TinChiThucHanh TINYINT,
	MaKhoa CHAR(4) FOREIGN KEY REFERENCES KHOA(MaKhoa),
)
GO

CREATE TABLE DIEUKIEN
(
	MaMonHoc VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MaMonHoc),
	MaMonHocTruoc VARCHAR(10),
	PRIMARY KEY (MaMonHoc, MaMonHocTruoc),
)
GO
CREATE TABLE GIANGDAY
(
	MaLop CHAR(4) FOREIGN KEY REFERENCES LOP(MaLop),
	MaMonHoc VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MaMonHoc),
	MaGiaoVien CHAR(4) FOREIGN KEY REFERENCES GIAOVIEN(MaGiaoVien),
	HocKy TINYINT,
	Nam SMALLINT,
	TuNgay SMALLDATETIME,
	DemNgay SMALLDATETIME,
	PRIMARY KEY (MALOP, MaMonHoc),
)
GO


CREATE TABLE KETQUATHI
(
	MaHocVien CHAR(4) FOREIGN KEY REFERENCES HOCVIEN(MaHocVien),
	MaMonHoc VARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MaMonHoc),
	LanThi TINYINT,
	NgayThi SMALLDATETIME,
	Diem NUMERIC(4,2),
	KetQua VARCHAR(10),
	PRIMARY KEY(MaHocVien, MaMonHoc, LanThi),
)
GO
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(60)
GO

ALTER TABLE HOCVIEN
ADD DIEMTB NUMERIC(4,2)
GO

ALTER TABLE HOCVIEN
ADD XEPLOAI VARCHAR(10)
GO
--Câu 3
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GioiTinh CHECK(GioiTinh IN ('NAM','NU'))
GO
--Câu 4
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_Diem CHECK
(
	DIEM BETWEEN 0 AND 10 AND
	LEN(SUBSTRING(CAST(DIEM AS VARCHAR), CHARINDEX('.', DIEM) +1,1000))>=2
)
GO
--Câu 5
ALTER TABLE KETQUATHI 
ADD CONSTRAINT CK_KUA CHECK(KetQua = IIF( DIEM BETWEEN 5 AND 10, 'DAT', 'KHONG DAT'))
GO

--Câu 6
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_SoLanThi CHECK(LANTHI <= 3)
GO

--Câu 7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HocKy CHECK(HocKy  BETWEEN 1 AND 3)
GO

--Câu 8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HocVi CHECK(HocVi IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))
GO
